@extends('layouts/adminUserForm')
@section('pageTitle','Edit Admin')
@section('formUrl','admin/'.$admin->id.'/edit/restore')
@section('method','patch')
@section('nameValue',$admin->name)
@section('emailValue',$admin->email)
@section('readonly','readonly')
@section('passwordPlaceholder','Can not change')
@section('buttonColor','success')
@section('buttonText','Edit') 