@extends('layouts/adminUserForm')
@section('pageTitle','Delete Admin')
@section('formUrl','admin/'.$admin->id.'/destroy/delete')
@section('method','delete')
@section('nameValue',$admin->name)
@section('readonlyName','readonly')
@section('emailValue',$admin->email)
@section('readonlyEmail','readonly')
@section('readonly','readonly')
@section('passwordPlaceholder','Can not confirm')
@section('buttonColor','danger')
@section('buttonText','Delete') 