@extends('layouts/adminUserForm')
@section('pageTitle','Edit Account')
@section('formUrl','user/'.$user->id.'/edit/restore')
@section('method','patch')
@section('nameValue',$user->name)
@section('emailValue',$user->email)
@section('readonly','readonly')
@section('passwordPlaceholder','Can not change')
@section('buttonColor','success')
@section('buttonText','Edit') 